"""Typed, bilingual configuration. Unknown fields fail closed."""
import copy, math
GROUPS = [
('general','基础偏好','Preferences'),('markets','市场','Markets'),('calendar','时段与扫描','Sessions & scanning'),('data','行情','Market data'),('universe','股票范围','Stock universe'),('crypto','Crypto范围','Crypto universe'),('golden','金叉','Golden cross'),('independent','独立策略','Independent strategies'),('filters','确认与排序','Confirmation'),('signals','信号周期','Signal lifecycle'),('capital','资金','Capital'),('fees','费用与单位','Fees & units'),('risk','风险','Risk'),('drawdown','回撤','Drawdown'),('exits','退出','Exits'),('execution','执行','Execution'),('alerts','提醒','Alerts'),('review','验证','Validation'),('backup','数据管理','Data management'),('deployment','部署','Deployment')]
FIELDS=[]
def f(group,key,zh,en,default,kind='number',lo=None,hi=None,options=None,supported=True):
 FIELDS.append(dict(group=group,key=key,zh=zh,en=en,default=default,type=kind,min=lo,max=hi,options=options,supported=supported))
f('general','language','语言','Language','zh','select',options=['zh','en'])
f('general','timezone','显示时区','Display time zone','Asia/Kuala_Lumpur','select',options=['Asia/Kuala_Lumpur','UTC','America/New_York','Asia/Hong_Kong','Asia/Tokyo'])
f('markets','enabled_markets','启用市场（逗号分隔）','Active markets (comma separated)','MY,US','text')
f('markets','live_markets','股票实盘记录市场','Stock live ledger markets','MY','text')
f('calendar','schedule','扫描时点（尚未支持自动任务）','Scan times (scheduler unavailable)','09:30,11:00,15:00,16:15','text',supported=False)
f('calendar','automatic_scan','自动扫描（未接入）','Automatic scanning (unavailable)',False,'bool',supported=False)
f('data','max_age_hours','报价有效期（小时）','Quote validity (hours)',24,lo=.1,hi=240)
f('data','history_min','最少K线','Minimum candles',60,lo=30,hi=1000)
f('data','timeout','网络超时（秒）','Network timeout (seconds)',8,lo=2,hi=20)
f('universe','sectors','重点板块','Priority sectors','AI,Semiconductors,Memory,Green energy,Construction,Infrastructure','text')
f('universe','watchlist','自选股（逗号分隔；空=全部导入股）','Watchlist (empty = all imported)','', 'text')
f('universe','excluded','排除代码','Excluded symbols','','text')
f('crypto','pairs','自选交易对（空=全部导入）','Pair watchlist (empty = all imported)','','text')
f('crypto','timeframe','Crypto默认周期','Crypto default timeframe','4h','select',options=['4h','1d'])
f('golden','ema_fast','EMA快线','Fast EMA',8,lo=2,hi=100)
f('golden','ema_slow','EMA慢线','Slow EMA',21,lo=3,hi=200)
f('golden','ema_enabled','EMA金叉','EMA crossover',True,'bool')
f('golden','macd_enabled','MACD金叉','MACD crossover',True,'bool')
f('golden','macd_fast','MACD快线','MACD fast',12,lo=2,hi=50)
f('golden','macd_slow','MACD慢线','MACD slow',26,lo=3,hi=100)
f('golden','macd_signal','MACD信号线','MACD signal',9,lo=2,hi=50)
f('golden','trend_filter','SMA趋势过滤','SMA trend filter',False,'bool')
f('golden','trend_length','SMA周期','SMA length',50,lo=5,hi=200)
f('independent','breakout_enabled','突破策略','Breakout strategy',True,'bool')
f('independent','breakout_length','突破回看（不含当前K）','Breakout lookback (prior bars)',20,lo=5,hi=100)
f('independent','breakout_buffer','突破缓冲 %','Breakout buffer %',.2,lo=0,hi=10)
f('independent','pullback_enabled','回踩策略','Pullback strategy',True,'bool')
f('independent','pullback_tolerance','回踩容差 %','Pullback tolerance %',1,lo=.1,hi=10)
f('filters','volume_length','均量周期','Volume lookback',20,lo=5,hi=100)
f('filters','min_rvol','最低相对成交量','Minimum relative volume',1.2,lo=0,hi=10)
f('filters','min_turnover','最低平均成交额（报价币）','Minimum average turnover (quote)',0,lo=0,hi=1e12)
f('filters','min_score','最低质量分（非概率）','Minimum quality score (not probability)',50,lo=0,hi=100)
f('filters','min_rr','最低净盈亏比（须大于）','Minimum net R/R (must exceed)',1.5,lo=.1,hi=20)
f('filters','max_results','每组最多结果','Maximum per group',10,lo=1,hi=100)
f('signals','fresh_bars','金叉有效K线数','Crossover freshness bars',3,lo=1,hi=20)
f('capital','fx_to_myr','报价币→MYR汇率','Quote currency → MYR FX',1,lo=.000001,hi=10000)
f('capital','fx_currency','汇率对应报价币','FX quote currency','MYR','text')
f('fees','fees_verified','费用已核实','Fees verified',False,'bool')
f('fees','fee_rate','单边佣金 %','Commission per side %',0,lo=0,hi=10)
f('fees','fee_min','最低单边佣金（报价币）','Minimum commission (quote)',0,lo=0,hi=1000)
f('fees','levy_rate','单边其他费用 %','Other charges per side %',0,lo=0,hi=10)
f('fees','slippage_bps','单边滑点基点','Slippage per side (bps)',10,lo=0,hi=1000)
f('fees','lot','数量步长','Quantity step',100,lo=.00000001,hi=100000)
f('fees','min_notional','最小订单金额（报价币）','Minimum order notional (quote)',0,lo=0,hi=1e6)
f('fees','fee_source','费用依据与生效日期','Fee source & effective date','','text')
f('risk','risk_pct','单笔默认风险 %','Risk per trade %',.5,lo=.01,hi=1.999)
f('risk','total_risk_pct','组合计划风险 %','Portfolio planned risk %',2,lo=.01,hi=5)
f('risk','max_positions','最大持仓数','Maximum positions',5,lo=1,hi=5)
f('risk','concentration_pct','单资产资金上限 %','Single asset allocation cap %',35,lo=1,hi=100)
f('risk','sector_pct','同板块资金上限 %','Sector allocation cap %',60,lo=1,hi=100)
f('risk','cash_reserve_pct','现金保留 %','Cash reserve %',0,lo=0,hi=90)
f('risk','risk_confirmed','独立风险设置已确认','Independent risk settings confirmed',True,'bool')
f('drawdown','warning_pct','回撤预警 %','Drawdown warning %',3,lo=.1,hi=20)
f('drawdown','pause_pct','回撤暂停 %','Drawdown pause %',5,lo=.2,hi=30)
f('drawdown','warning_multiplier','预警后风险倍数','Risk multiplier after warning',.5,lo=.1,hi=1)
f('exits','stop_pct','初始止损距离 %','Initial stop distance %',5,lo=.1,hi=50)
f('exits','target_r','目标R倍数','Target R multiple',2,lo=.1,hi=20)
f('exits','exit_mode','默认退出模式','Default exit mode','radar','select',options=['radar','period','fixed','trailing','combined'])
f('exits','holding_bars','持有期限（日线=交易日；Crypto=K线数）','Holding bars (stock daily = sessions)',10,lo=3,hi=20)
f('exits','take_pct','T1卖出比例 %','T1 exit allocation %',50,lo=1,hi=100)
f('exits','trailing_pct','余仓移动止损距离 %','Trailing distance %',5,lo=.1,hi=50)
f('execution','approval','券商审批下单（未接通）','Broker approval execution (not connected)',False,'bool',supported=False)
f('execution','manual','手动成交录入','Manual fill recording',True,'bool')
f('alerts','alerts_enabled','应用内风险提醒','In-app risk alerts',True,'bool')
f('alerts','email','外发通知（未接通）','External notifications (not connected)',False,'bool',supported=False)
f('review','minimum_samples','最低样本外交易数','Minimum OOS trades',100,lo=30,hi=10000)
f('review','target_win','净胜率目标 %','Net win rate target %',80,lo=1,hi=100)
f('review','target_return','股票年收益目标 %','Stock annual return target %',55,lo=0,hi=1000)
f('review','win_gate','胜率硬门槛（当前无验证信号将被排除）','Hard win-rate gate (unvalidated signals excluded)',False,'bool')
f('backup','scheduled_backup','定时备份（未实现）','Scheduled backup (unavailable)',False,'bool',supported=False)
f('deployment','github','GitHub仓库（仅元数据）','GitHub repository (metadata only)','https://github.com/accentgrove/AstraFin','text')
DEFAULT = {x['key']:x['default'] for x in FIELDS}
def initial():
 stock=copy.deepcopy(DEFAULT)
 crypto=copy.deepcopy(DEFAULT);crypto.update(fx_to_myr=1,fx_currency='USD',lot=.00000001,risk_confirmed=False)
 return {'schema_version':1,'revision':0,'stocks':stock,'crypto':crypto}
def validate(data):
 if set(data)!={'schema_version','revision','stocks','crypto'} or data['schema_version']!=1: raise ValueError('CONFIG_SCHEMA')
 for asset in ['stocks','crypto']:
  c=data[asset]
  if set(c)!=set(DEFAULT): raise ValueError('CONFIG_FIELDS')
  for x in FIELDS:
   v=c[x['key']]
   if not x['supported'] and v!=x['default']: raise ValueError('UNSUPPORTED')
   if x['type']=='number':
    if type(v) not in (int,float) or not math.isfinite(v) or (x['min'] is not None and v<x['min']) or (x['max'] is not None and v>x['max']): raise ValueError('CONFIG_RANGE:'+x['key'])
    if x['key'] in ['ema_fast','ema_slow','macd_fast','macd_slow','macd_signal','trend_length','breakout_length','volume_length','fresh_bars','max_results','history_min','max_positions','minimum_samples','holding_bars'] and int(v)!=v: raise ValueError('CONFIG_INTEGER')
   elif x['type']=='bool' and type(v)!=bool: raise ValueError('CONFIG_TYPE')
   elif x['type'] in ['text','select'] and (not isinstance(v,str) or len(v)>2000): raise ValueError('CONFIG_TYPE')
   if x['options'] and v not in x['options']: raise ValueError('CONFIG_OPTION')
  if c['ema_fast']>=c['ema_slow'] or c['macd_fast']>=c['macd_slow'] or c['warning_pct']>=c['pause_pct']: raise ValueError('CONFIG_ORDER')
  if c['fees_verified'] and not c['fee_source'].strip(): raise ValueError('FEE_SOURCE')
  if not set(c['enabled_markets'].split(',')) <= {'MY','US','HK','CN','JP','SG','TW'}: raise ValueError('MARKET')
  if not set(c['live_markets'].split(',')) <= set(c['enabled_markets'].split(',')): raise ValueError('MARKET')
 return data
